<?php $base_path = '../'; ?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>SVN/Git Wrangling, Laravel Rage, and CET Headaches | Blog | Raphaël Reck</title>
  <meta name="description" content="This week was chaos and cleanup: migrating SVN to Git, Laravel app deployment issues, and CET webform problems in production."/>
  <link rel="canonical" href="https://raphaelreck.com/blog/SVNgit.php"/>
  <link rel="stylesheet" href="../style.css"/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">

  <meta property="og:type" content="article"/>
  <meta property="og:title" content="SVN/Git Wrangling, Laravel Rage, and CET Headaches"/>
  <meta property="og:url" content="https://raphaelreck.com/blog/SVNgit.html"/>
  <meta property="og:site_name" content="Raphaël Reck"/>
  <meta property="article:published_time" content="2025-07-06T00:00:00+02:00"/>
</head>
<body>
  <button id="theme-toggle" class="theme-toggle" aria-label="Toggle theme"><i class="fas fa-moon"></i></button>
  <div class="container">
    <?php include __DIR__ . '/../includes/navigation.php'; ?>

    <main>
      <article class="blog-post">
        <header class="post-header">
          <h1>SVN/Git Wrangling, Laravel Rage, and CET Headaches</h1>
          <p class="post-meta">
            <time datetime="2025-07-06">July 6, 2025</time>
          </p>
        </header>

        <p>This week was chaos and cleanup. Here's the damage:</p>

        <h3>Git vs SVN: The Migration No One Wants to Do</h3>
        <p>
          Tried migrating an old SVN project (AzurAgent) to GitLab. Did care about the history  -  just wanted to mirror the damn folder structure.
          But Git decided to throw a tantrum: thought I was deleting files instead of moving them. Line endings (CRLF/LF) made diffs unreadable. Classic.
        </p>
        <p>
          Lesson: Git doesn't forgive structural violence. Plan your moves like a game of chess, or prepare to revert everything with tears in your eyes.
        </p>

        <h3>Laravel: The Bidding Site and Codex Fatigue</h3>
        <p>
          I pushed live a Laravel app generated by Codex  -  a bidding system for a house. Deployed it at
          <a href="https://julien.raphaelreck.com" target="_blank">julien.raphaelreck.com</a>.
        </p>
        <p>This was my first time using Laravel for a project. Thanks GPT.</p>
        <p>Issues, as expected:</p>
        <ul>
          <li>Root URL 404'd even though child routes worked.</li>
          <li>Images failed to load  -  turns out the photos folder wasn't in <code>/public</code>.</li>
          <li>Codex-generated registration form had no validation for phone or email. No feedback. No regex. Just vibes.</li>
          <li>Dropdown fields broke silently. Inspect, guess, cry, repeat.</li>
        </ul>
        <p>
          Reminder: Don't trust AI scaffolding tools to finish the job. They're good starters  -  but lazy interns if left alone.
        </p>

        <h3>CET Form: Webservice Shenanigans in Production</h3>
        <p>
          On the AzurAgent side, we pushed the CET webform to VA for live testing. Tried to submit a 5-day annual leave transfer  -  frontend looked fine, but backend didn't call the WS or trigger the fallback email.
        </p>
        <p>Suspected areas:</p>
        <ul>
          <li>Silent WS push failure (PUSH_DEMANDE_ACTIONCET)</li>
          <li>Fallback notification logic not firing</li>
          <li>No way to trace unless I dig through VA logs</li>
        </ul>
        <p>
          Deployed, tested, and now chasing ghosts. It works locally. On VA? Shrugs.
        </p>

        <h3>Final Thought: Stop the Framework Madness</h3>
        <p>
          Every time I touch a framework, something breaks that HTML never asked for. Bloat creeps in. Pages slow down. Errors multiply.
          We used to build websites. Now we build excuses.
        </p>
        <p>If you want something to work <strong>keep it simple</strong>.</p>

        <p style="font-family: monospace; color: gray;">
          // no JS frameworks were harmed in the making of this log
        </p>

        <hr>
        <br>
        <button class="link-btn"><a href="index.php">← Back to Blog Index</a></button>
      </article>
    </main>

    <?php include __DIR__ . '/../includes/footer.php'; ?>
  </div>

  
  <?php include __DIR__ . '/../includes/mobile-menu.php'; ?>
</body>
</html>
</body>
</html>
